In [1]:
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.preprocessing import KBinsDiscretizer
import pandas as pd
import os
import numpy as np

In [2]:
mv_df = pd.read_csv(os.path.join("..", "Resources", "movie_metadata_adjusted_revenue.csv"))
mv_df['popularity'] = mv_df['popularity'].astype(int)
mv_df['revenue'] = mv_df['revenue'].str.replace(',','').astype(float).astype(int)
mv_df = mv_df.drop(columns={'Unnamed: 0'})
mv_df.head()

title    budget  popularity  release_date  \
0                    The Godfather   6000000          41          1972   
1         The Shawshank Redemption  25000000          51          1994   
2                       Fight Club  63000000          63          1999   
3                 Schindler's List  22000000          41          1993   
4  One Flew Over the Cuckoo's Nest   3000000          35          1975   

      revenue  runtime  vote_average  vote_count  
0  1499126346      175           8.5        6024  
1    48899552      142           8.5        8358  
2   154791744      139           8.3        9678  
3   568672494      195           8.3        4436  
4   517964907      133           8.3        3001

In [3]:
X, y = make_classification(n_samples=200, n_features=6, n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
rf = RandomForestClassifier(max_depth=2, random_state=0)
rf.fit(X, y)
# rf.predict(np.array([8,1]).reshape(-1, 1))
# model = rf.predict(np.array([8,1])).shape
# model = np.array([8,1]).shape
# print(model)

/Users/brian.abbe/anaconda3/envs/Pythondata/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [4]:
enc = KBinsDiscretizer(n_bins=8, encode='ordinal')
enc.fit(X)
result = enc.transform(X)
print(result)

[[0. 1. 0. 6. 3. 3.]
 [2. 4. 7. 6. 5. 4.]
 [0. 0. 7. 7. 6. 6.]
 ...
 [6. 6. 0. 5. 1. 0.]
 [2. 4. 7. 5. 1. 0.]
 [2. 4. 6. 1. 7. 6.]]


In [14]:
# print(result[:,1:2])
X[:,2:3] = result[:,2:3]
X[:,3:4] = result[:,3:4]
X[:,5:6] = result[:,5:6]
X[:,7:8] = result[:,7:8]
X[:,8:9] = result[:,8:9]
# X[:,2:3] = result[:,2:3]

print(X[9][4])

-0.7826291558275251


In [6]:
rf2 = RandomForestClassifier(max_depth=3, random_state=0)
rf2.fit(X, y)
print(rf2.feature_importances_)

[0.05845772 0.82927202 0.02396409 0.0285356  0.05171314 0.00805742]


/Users/brian.abbe/anaconda3/envs/Pythondata/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [7]:
sorted(zip(rf2.feature_importances_, mv_df.title), reverse=True)

[(0.829272024866647, 'The Shawshank Redemption'),
 (0.05845772463860185, 'The Godfather'),
 (0.05171313914592953, "One Flew Over the Cuckoo's Nest"),
 (0.028535599740821004, "Schindler's List"),
 (0.023964094719163928, 'Fight Club'),
 (0.008057416888836598, 'The Dark Knight')]

In [8]:
# rf = RandomForestClassifier(n_estimators=200)
# rf = rf.fit(mv_df.revenue, mv_df.vote_average)
# rf.score(mv_df.revenue, mv_df.vote_average)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [9]:
rf2 = rf2.fit(X_train, y_train)
rf2.score(X_test, y_test)

0.96